site_name: Sam Test Feb 15 from Mac

theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: light green

# Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

